# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Test Flight"
  lane :test_flight do
    # match()

    gym(
      configuration: 'Release',
      workspace: 'Runner.workspace',
      scheme: 'Runner',
      export_method: 'app_store'
      #provisioningProfiles
    )

    pilot(
      #apple_id
      #app_identifier
      ipa: './Runner.ipa'
    )
  end
end
