# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy to Google Play Closed Beta"
  lane :closed_beta do
    upload_to_play_store(
      track: 'Closed beta',
      #aab: '../build/app/outputs/bundle/release/app.aab',
      aab: '../build/app/outputs/bundle/debug/app.aab',#TODO: update to release
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: 'draft',
      version_code: 1
    )
  end
end
