name: Continuous Delivery

on:
  workflow_dispatch

jobs:
  deploy_android:
    name: Deploy Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Flutter clean
        run: flutter clean
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Analyze files
        run: flutter analyze .
      - name: Generate apk
        run: flutter build apk --debug #TODO: update to release
      - name: Fastlane upload
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: closed_beta
          subdirectory: android